[project]
name = "ip-rivian-otel-public"
version = "0.1.0"
description = "This project is a simple demonstration of creating an OTLP collector for Rivian vehicle data in Python"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
